sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
- 2.5.3
bundler_args: "--without development"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: LR93nLd5afxgMGNC4bWmnY5dw0vY1gqSBbp6D7HyVmeT1fCYk8ZxqQEDJd5gX9LcFlkwL4kLjNvCrMMODNBNfoGuUWPA3ncpFWGZhJtX/yNCQQno0DcZUNyDh/zPiuwdxxXqsNy+LILb0TFfb2bKqm2OPkyuUTLl8F9cKMopAZ+aKBD1K3cCngqI0lNK2fLMP0cE8iJUEndUgJdXrONoLLTtn0Mk8kH/AcCvuGaqI9qAg6jNQoEIfBESC00ByrGMRqYzhG2DyzbgpEiVdNsS5naejjRNRWKnVKq6FAhXyjx1p16gI385oywB2VQvWEF1dyXS1Sq+Uq59YIcGRyfqe3+bIMov3nBZukXMMqqtiFSogYEvEgy/GDVEd93SNUfKw7+dv368o0uCluWqqOunC8OAMakWDrlku8RLQtQawQrXGzV2tKeCd6Nogo1af5eL1q7IQv2vUSPdEX02Gunn2hocfKX7ax9QoEsSPkUe6pu+EgoxB/LOCEbviAoBB/XWYPWm1kcZHtnqpO4fjjXb7vob4WjiwpqFXK/3iUzZv0Ydp80sq1dfLtobiQ/QspIjXWI+aKedspuwVk9gUbXE3SgCuTnVEQlTAjnIU1ydgkdO0FPIhkQoWD7oj1uRQjWD8VaaN07Zw/midPZURSVy17MXDyKWc2N6VcLfMXW3088=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
jobs:
  include:
  - stage: Test
    before_script:
    - npm install -g sass-lint htmllint-cli markdownlint-cli
    script:
    - JEKYLL_ENV=production bundle exec jekyll build
    - markdownlint _posts _drafts _pages README.md
    - bundle exec htmlproofer _site --allow-hash-href --assume-extension --url-ignore
      "/localhost/" --http-status-ignore "999" --http-status-ignore "302"
  - stage: Github Release
    script:
    - JEKYLL_ENV=production bundle exec jekyll build
    deploy:
      provider: pages
      local-dir: "./_site"
      target-branch: master
      name: Travis Deployment Bot
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      on:
        branch: master
