sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.3
bundler_args: --without development
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
jobs:
  include:
    - stage: Test
      before_script:
        - npm install -g sass-lint htmllint-cli markdownlint-cli
      script:
        - JEKYLL_ENV=production bundle exec jekyll build
        - bundle exec htmlproofer _site --allow-hash-href --assume-extension --url-ignore "/localhost/" --http-status-ignore "999" --http-status-ignore "302"
    # - stage: Github Release
    #   script:
    #     - JEKYLL_ENV=production bundle exec jekyll build
    #   deploy:
    #     provider: pages
    #     local-dir: ./_site
    #     target-branch: master
    #     name: Travis Deployment Bot
    #     skip-cleanup: true
    #     github-token: $GITHUB_TOKEN
    #     keep-history: true
    #     on:
    #       branch: release