# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ruio e franz
description: Villa Frassanelle, 8 Settembre 2019
url: "http://ruioefranz.com" # the base hostname & protocol for your site, e.g. http://example.com

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Benvenuti!
  text: |
    Grazie per essere arrivati sul sito web del matrimonio
# - displayed at the bottom
closing-head: _Your closing_
closing-para: _Your detailed closing_

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

social:
  github: https://github.com/maruina/ruioefranz.com
  email: matteo.ruina@gmail.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
exclude: [vendor]